spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/parking_area?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  #    useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

server:
  servlet:
    context-path: /parkingarea

